MAX_GENOMES = 1000

FILE_FORMAT = "fasta"

RAW_DATA_FOLDER_PATH = "data/raw"
GENOMES_RAW_DATA_FILE_PATH = f"{RAW_DATA_FOLDER_PATH}/genomes"
PROTEINS_RAW_DATA_FILE_PATH = f"{RAW_DATA_FOLDER_PATH}/proteins"

ENTREZ_EMAIL = "Your.Name.Here@example.org"
